#!/bin/bash
# find files and only filter with .pdf file extension
pdfs=$(find . -maxdepth 1 -type f -name "*.pdf" -printf "./%f\n")
echo "$pdfs"

# Run pdftk with the list of PDF filenames
pdftk $pdfs cat output combined.pdf